### ISSUE TITLE
SGB support

### ISSUE THREAD

**Issue by zlago** [GreenAndEievui/vuiiger-engine#4]
i dont really know how to format the body of this issue
- [ ] asset conversion, figure out how to get usable SGB data from assets
- [ ] SGB init, detect SGB then upload palette and attribute data
- [ ] SGB borders, either upload one at init and never touch it or make it configurable per-floor
- [ ] playfield colorisation (color during gameplay)
- [ ] cutscene colorisation (yknow, like how kirby 2 has more colorful cutscenes than gameplay)

**Comment by eievui5** [comment]
- Assuming RGBGFX can't already do this, we could include superfamiconv as an optional dependency and allow the user to disable SGB support if needed.
  - Alternatively, it wouldn't be terribly hard to throw together a rust program for what esprit needs so there's no extra dependencies.
- I assume this is just a flag we set at launch, and then check when appropriate?
- Generic border, based on the title screen.
  - Ideally, each level would get a border.  Drawing all of that would probably be a challenge though. TBD
- During gameplay, the hud can be colored according to the user's current theme, and the playfield can be given a single color depending on the level (in order: green, yellow-green, blue, orange, grey, purple)
- Retroactively adding SGB colors to cutscenes would be a lot of work and I don't know if it's feasible. On the other hand, the title screen and world map could easier be given colors.
